language: node_js
node_js:
  - 14.6.0
script:
  - "npm run test"
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  api_key:
    secure: 8dcc8003-5b5d-4fd6-b2bf-e9d630f90a1e
  app: sdm-project
  on: develop
