language: node_js
node_js:
  - 14.6.0
script:
  - "npm run test"
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  api_key:
    secure: 0eebccad-5b0e-4138-aa10-1a0859c0ff30
  app: sdm-project

